---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  annotations:
    argocd/app-name: hello-world
    backstage.io/kubernetes-id: hello-kustomize-webapp
    backstage.io/kubernetes-namespace: backstage-test
  tags:
    - springboot
    - api
    - microservice
spec:
  type: service
  lifecycle: production
  owner: user:default/user1
