---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  annotations:
    argocd/app-name: hello-world
    backstage.io/kubernetes-id: hello-world
    backstage.io/kubernetes-namespace: backstage-test
    tekton.dev/cicd: "true"
    janus-idp.io/tekton: hello-world
    quay.io/repository-slug: 'ralvarezbackstage/hello-world'
    sonarqube.org/project-key: "sonarqube-dev/hello-world"
  tags:
    - springboot
    - api
    - microservice
spec:
  type: service
  lifecycle: production
  owner: user:default/user1
