---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  annotations:
    goharbor.io/repository-slug: ralvarez/test
  tags:
    - springboot
    - api
    - microservice
spec:
  type: service
  lifecycle: production
  owner: user:default/user1
