---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  annotations:
    goharbor.io/repository-slug: ralvarez/test
    jenkins.io/job-full-name: alfred.deployer.uuaa.listener
    backstage.io/kubernetes-id: 'hello-world'
    backstage.io/kubernetes-namespace: 'ris-dev'
    sonarqube.org/project-key: dev/core-padrones
  tags:
    - springboot
    - api
    - microservice
spec:
  type: service
  lifecycle: production
  owner: user:default/user1
