---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  annotations:
    goharbor.io/repository-slug: ralvarez/test
    jenkins.io/job-full-name: escritorio-medico-v2/alfred.builder.ia.front-escv2-p
    backstage.io/kubernetes-id: 'hello-world'
    backstage.io/kubernetes-namespace: 'ris-dev'
    sonarqube.org/project-key: dev/ar.com.smg:java-sprint-boot-template
    argocd/app-name: bus-dev
    argocd/instance-name: rosa-dev
    backstage.io/techdocs-ref: dir:.
  tags:
    - springboot
    - api
    - microservice
spec:
  type: service
  lifecycle: production
  owner: user:default/user1
